import com.vanniktech.maven.publish.JavadocJar
import com.vanniktech.maven.publish.KotlinMultiplatform
import com.vanniktech.maven.publish.SourcesJar
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.dsl.abi.ExperimentalAbiValidation
import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget
import org.jetbrains.kotlin.konan.target.KonanTarget

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    // The KMP Android target has no lint task of its own; this plugin provides `lint` for the
    // module, configured by the `lint {}` block in the android target below.
    alias(libs.plugins.android.lint)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.maven.publish)
    alias(libs.plugins.dokka)
    // Screenshot tests. Renders composables on the JVM under Robolectric — no emulator, so the
    // visual regression suite runs in the same fast CI job as the unit tests.
    //
    // Roborazzi rather than Paparazzi: Paparazzi's layoutlib is pinned per release and lags the
    // current compileSdk on its stable line, which is not something to gate a library's CI on.
    alias(libs.plugins.roborazzi)
}

kotlin {
    // Every declaration in a published library must state its visibility and its return type.
    // Without this, a `val` that was meant to be internal ships as public API and can never be
    // removed without breaking consumers — which is exactly what the ABI check then locks in.
    explicitApi()

    android {
        namespace = "com.ezzy.ccp"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()

        compilerOptions { jvmTarget.set(JvmTarget.JVM_11) }

        // The library's strings, plurals and their translations are Compose Multiplatform
        // resources (src/commonMain/composeResources). On Android they are packaged as assets,
        // which the KMP Android target only does when resources are enabled.
        androidResources { enable = true }

        optimization {
            consumerKeepRules.publish = true
            consumerKeepRules.file("consumer-rules.pro")
        }

        lint {
            targetSdk = libs.versions.android.targetSdk.get().toInt()
            // A lint regression in a library is a lint regression in every consumer, so CI treats
            // warnings as failures rather than letting them accumulate.
            warningsAsErrors = true
            abortOnError = true
            checkReleaseBuilds = true
            // "A newer version of X is available" is not a regression in the library: it turns
            // red on the day AGP or Gradle ships a release, with no change to this repository, and
            // would make every build fail retroactively. Toolchain upgrades are deliberate commits.
            disable += setOf("AndroidGradlePluginVersion", "GradleDependency", "NewerVersionAvailable")
            // Deliberately no baseline: the module is at zero findings, and a baseline file would
            // let the next regression be recorded rather than fixed. (SARIF reports are always
            // generated by AGP 9.)
        }

        // JVM unit tests: commonTest runs here too, plus the Robolectric screenshot suite and the
        // Android-only tests in androidHostTest.
        withHostTest {
            isIncludeAndroidResources = true
            isReturnDefaultValues = true
        }

        withDeviceTest {
            instrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
            // The test APK needs a modern targetSdk of its own. Left unset it falls back to minSdk
            // (24), which is old enough that some OS builds route the test app through the legacy
            // permission-review flow — a GrantPermissionsActivity dialog steals focus right as the
            // test Activity launches, and Compose UI tests fail with "No compose hierarchies found".
            targetSdk { version = release(libs.versions.android.targetSdk.get().toInt()) }
        }
    }

    // Apple-silicon simulators and devices. Compose Multiplatform no longer publishes iosX64.
    val iosTargets = listOf(iosArm64(), iosSimulatorArm64())
    iosTargets.forEach { target -> target.bindLibPhoneNumber() }

    // Guards the published ABI. Each target's public API is dumped under ccp/api/ and
    // `checkKotlinAbi` (wired into `check` and CI) fails when the compiled surface drifts from it.
    // Changing public API is then a deliberate, reviewable commit: run `./gradlew :ccp:updateKotlinAbi`
    // and commit the diff.
    @OptIn(ExperimentalAbiValidation::class)
    abiValidation {
        filters {
            exclude {
                // @Preview composables and the sample screen are examples, not API — they are
                // public only because Compose tooling requires it.
                byNames.add("com.ezzy.ccp.countrypicker.sample.**")
            }
        }
    }

    compilerOptions {
        freeCompilerArgs.addAll(
            // ModalBottomSheet, clickable Surface and stickyHeader are still marked experimental but
            // are the correct Material 3 / Foundation APIs for this component. Opting in once here is
            // clearer than annotating every composable that touches them.
            "-opt-in=androidx.compose.material3.ExperimentalMaterial3Api",
            "-opt-in=androidx.compose.foundation.ExperimentalFoundationApi",
            // expect/actual classes are still Beta. The library has exactly one, internal: the
            // platform phone-number handle (PlatformPhoneNumber) that PhoneNumberBackend passes around.
            "-Xexpect-actual-classes",
        )
    }

    sourceSets {
        // The iOS actuals call Foundation, UIKit and the libPhoneNumber-iOS bindings directly.
        // (Applied to every iOS source set: Kotlin requires a source set's opt-ins to be repeated
        // on each source set that depends on it.)
        matching { it.name.startsWith("ios") }.configureEach {
            languageSettings.optIn("kotlinx.cinterop.ExperimentalForeignApi")
            languageSettings.optIn("kotlinx.cinterop.BetaInteropApi")
        }
        commonMain.dependencies {
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.ui)
            implementation(libs.compose.material3)
            implementation(libs.compose.components.resources)
            implementation(libs.compose.ui.tooling.preview)
            implementation(libs.kotlinx.coroutines.core)
        }
        androidMain.dependencies {
            implementation(libs.lib.phone)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
        }
        getByName("androidHostTest").dependencies {
            implementation(libs.junit)
            implementation(libs.robolectric)
            implementation(libs.roborazzi)
            implementation(libs.roborazzi.compose)
            implementation(libs.roborazzi.rule)
            implementation(libs.androidx.compose.ui.test.junit4)
            implementation(libs.androidx.compose.ui.test.manifest)
        }
        getByName("androidDeviceTest").dependencies {
            implementation(libs.androidx.junit)
            implementation(libs.androidx.espresso.core)
            implementation(libs.androidx.compose.ui.test.junit4)
            implementation(libs.androidx.compose.ui.test.manifest)
            implementation(libs.kotlinx.coroutines.test)
        }
    }
}

compose.resources {
    // The generated accessor is an implementation detail: hosts override strings through UiText,
    // never by reaching into the library's Res.
    packageOfResClass = "com.ezzy.ccp.resources"
    publicResClass = false
}

// ── libPhoneNumber-iOS ─────────────────────────────────────────────────────────────────────────
//
// On iOS the phone-number engine is libPhoneNumber-iOS — the Objective-C port of the same Google
// library the Android target uses, generated from the same metadata release (see the lib-phone
// comment in gradle/libs.versions.toml). Its sources are vendored under src/nativeInterop and
// compiled per target into a static archive that cinterop embeds in the klib, so consumers get it
// with the dependency: nothing to add to their Podfile, Package.swift or linker flags.

/** The `xcrun --sdk` name and clang target triple for each Kotlin/Native iOS target. */
fun KonanTarget.appleToolchain(): Pair<String, String> = when (this) {
    KonanTarget.IOS_ARM64 -> "iphoneos" to "arm64-apple-ios15.0"
    KonanTarget.IOS_SIMULATOR_ARM64 -> "iphonesimulator" to "arm64-apple-ios15.0-simulator"
    else -> error("No libPhoneNumber-iOS toolchain mapping for $this")
}

fun KotlinNativeTarget.bindLibPhoneNumber() {
    val (sdk, triple) = konanTarget.appleToolchain()
    val outputDir = layout.buildDirectory.dir("libphonenumber/$targetName")
    val buildArchive = tasks.register<Exec>("buildLibPhoneNumber${targetName.replaceFirstChar(Char::uppercase)}") {
        description = "Compiles the vendored libPhoneNumber-iOS into a static archive for $targetName."
        group = "build"
        val script = rootProject.layout.projectDirectory.file("scripts/build-libphonenumber-ios.sh")
        inputs.file(script).withPathSensitivity(PathSensitivity.RELATIVE)
        inputs.dir(layout.projectDirectory.dir("src/nativeInterop")).withPathSensitivity(PathSensitivity.RELATIVE)
        outputs.dir(outputDir)
        commandLine(script.asFile.absolutePath, sdk, triple, outputDir.get().asFile.absolutePath)
    }

    compilations.getByName("main").cinterops.create("libPhoneNumber") {
        definitionFile.set(layout.projectDirectory.file("src/nativeInterop/cinterop/libPhoneNumber.def"))
        // ccp_libphonenumber.h (in cinterop/) applies the same renames the archive was compiled
        // with before importing the libPhoneNumber-iOS headers, so the bindings name the prefixed
        // symbols the archive actually defines (CCPNBPhoneNumberUtil, …).
        includeDirs(
            layout.projectDirectory.dir("src/nativeInterop/cinterop"),
            layout.projectDirectory.dir("src/nativeInterop/libPhoneNumber-iOS/libPhoneNumber"),
            layout.projectDirectory.dir("src/nativeInterop/libPhoneNumber-iOS/libPhoneNumberInternal"),
        )
        extraOpts("-libraryPath", outputDir.get().asFile.absolutePath)
        tasks.named(interopProcessingTaskName) { dependsOn(buildArchive) }
    }
}

// ── Publishing ─────────────────────────────────────────────────────────────────────────────────
//
// Coordinates, POM metadata and signing flags all come from gradle.properties (GROUP,
// VERSION_NAME, POM_*), so the version number has exactly one home and the docs site, the
// published artifact and the README cannot drift apart.
//
// One Gradle-metadata publication fans out to ccp-android (AAR) and ccp-iosarm64 /
// ccp-iossimulatorarm64 (klibs). Gradle consumers depend on `io.github.ezekielwachira:ccp` and get
// the right one per target. The iOS klibs can only be built on macOS, so releases run there.
mavenPublishing {
    configure(
        KotlinMultiplatform(
            javadocJar = JavadocJar.Dokka("dokkaGeneratePublicationHtml"),
            sourcesJar = SourcesJar.Sources(),
        )
    )

    // Signing keys only exist on the release runner. Signing unconditionally would make every
    // local `publishToMavenLocal` fail.
    if (providers.gradleProperty("signingInMemoryKey").isPresent) {
        signAllPublications()
    }
}

// API reference (Dokka). Run `./gradlew :ccp:dokkaGenerate`; output lands in ccp/build/dokka/html.
// The published site (docs/ + this output under /api/) is built by .github/workflows/docs.yml.
dokka {
    moduleName.set("ccp")
    moduleVersion.set(
        providers.gradleProperty("docsVersion")
            .orElse(providers.gradleProperty("VERSION_NAME"))
    )

    dokkaSourceSets.configureEach {
        includes.from("Module.md")
        reportUndocumented.set(false)
        skipEmptyPackages.set(true)
        suppressGeneratedFiles.set(true)

        // @Preview composables and the sample screen are examples, not API.
        perPackageOption {
            matchingRegex.set("""com\.ezzy\.ccp\.countrypicker\.sample.*""")
            suppress.set(true)
        }

        val sourceSetDir = "src/${name}/kotlin"
        if (file(sourceSetDir).exists()) {
            sourceLink {
                localDirectory.set(file(sourceSetDir))
                remoteUrl("https://github.com/EzekielWachira/Country-Code-Picker/tree/main/ccp/$sourceSetDir")
                remoteLineSuffix.set("#L")
            }
        }

        externalDocumentationLinks.register("kotlinx-coroutines") {
            url("https://kotlinlang.org/api/kotlinx.coroutines/")
        }
    }

    pluginsConfiguration.html {
        footerMessage.set("© 2025 Ezekiel Wachira · MIT License")
    }
}

// ── libphonenumber metadata footprint (Android) ────────────────────────────────────────────────
//
// The libphonenumber jar ships three metadata blobs. This library only ever reaches
// PhoneNumberUtil and AsYouTypeFormatter, which need exactly one of them:
//
//   PhoneNumberMetadataProto            ~235 KB  required
//   ShortNumberMetadataProto             ~75 KB  only ShortNumberInfo reads it   — unused here
//   PhoneNumberAlternateFormatsProto     ~23 KB  only PhoneNumberMatcher reads it — unused here
//
// So Android consumers can strip ~99 KB from their APK with a `packaging { resources { excludes } }`
// rule (see the README and :app for the exact snippet). That advice is only safe while the library
// genuinely avoids those two entry points — and "we currently don't use it" is the kind of fact
// that quietly stops being true. This task makes it a build failure instead.
val forbiddenPhoneNumberApis = listOf(
    "ShortNumberInfo" to "needs ShortNumberMetadataProto, which consumers are told to exclude",
    "PhoneNumberMatcher" to "needs PhoneNumberAlternateFormatsProto, which consumers are told to exclude",
    "PhoneNumberOfflineGeocoder" to "pulls in the separate geocoder metadata artifact",
    "PhoneNumberToCarrierMapper" to "pulls in the separate carrier metadata artifact",
)

val verifyPhoneNumberMetadataFootprint = tasks.register("verifyPhoneNumberMetadataFootprint") {
    description = "Fails if the library starts using libphonenumber APIs whose metadata consumers are told to strip."
    group = "verification"

    val sources = fileTree("src") {
        include("commonMain/kotlin/**/*.kt", "androidMain/kotlin/**/*.kt")
    }
    inputs.files(sources).withPathSensitivity(PathSensitivity.RELATIVE)
    // No real output; a marker keeps the task up-to-date-able instead of re-running every build.
    val marker = layout.buildDirectory.file("reports/phonenumber-footprint.txt")
    outputs.file(marker)
    val moduleDir = projectDir

    doLast {
        val violations = sources.files.flatMap { file ->
            val text = file.readText()
            forbiddenPhoneNumberApis.mapNotNull { (api, why) ->
                if (text.contains(api)) "${file.relativeTo(moduleDir)} uses $api — $why" else null
            }
        }
        if (violations.isNotEmpty()) {
            error(
                buildString {
                    appendLine("libphonenumber metadata footprint check failed.")
                    appendLine()
                    violations.forEach { appendLine("  • $it") }
                    appendLine()
                    appendLine("Either drop the usage, or remove the corresponding exclusion from the")
                    appendLine("README and :app packaging rules — consumers following that advice would")
                    appendLine("otherwise ship an app that fails at runtime with a missing-metadata error.")
                }
            )
        }
        marker.get().asFile.apply {
            parentFile.mkdirs()
            writeText("ok: none of ${forbiddenPhoneNumberApis.map { it.first }} are referenced\n")
        }
    }
}

tasks.named("check") { dependsOn(verifyPhoneNumberMetadataFootprint) }

// ── Translation parity ─────────────────────────────────────────────────────────────────────────
//
// The README claims the bundled locales are complete, and every one of them was — until three
// strings were added to values/ and the translations were not updated in the same change. A blanket
// "every locale must be complete" lint would also fire on a *new* locale that is still being filled
// in, which would make contributing a translation a chicken-and-egg problem.
//
// This is the narrower rule that is actually wanted: an existing locale must stay complete. A
// brand-new one is free to land partial, and is only held to parity once it declares a name.
//
// It also rejects the two Android-resource habits that Compose Multiplatform resources do not
// support, both of which fail silently instead of at build time: a non-positional `%s` / `%d` (only
// the `%1$s` form is substituted, so the raw placeholder would reach the screen), and an escaped
// `\'` or `\"` (only `\n`, `\t`, `\uXXXX` and `\\` are unescaped, so the backslash would show).
val verifyTranslationParity = tasks.register("verifyTranslationParity") {
    description = "Fails when a bundled locale is missing a string that values/ defines, or uses unsupported syntax."
    group = "verification"

    val resDir = layout.projectDirectory.dir("src/commonMain/composeResources")
    inputs.dir(resDir).withPathSensitivity(PathSensitivity.RELATIVE)
    val marker = layout.buildDirectory.file("reports/translation-parity.txt")
    outputs.file(marker)

    doLast {
        val nameRegex = Regex("""<(?:string|plurals|string-array) name="([^"]+)"""")
        fun namesIn(file: File) = nameRegex.findAll(file.readText()).map { it.groupValues[1] }.toSet()

        val root = resDir.asFile
        val base = namesIn(File(root, "values/strings.xml"))
        val localeFiles = root.listFiles()
            .orEmpty()
            .filter { it.isDirectory && it.name.startsWith("values") }
            .sortedBy { it.name }
            .map { File(it, "strings.xml") }
            .filter { it.exists() }

        val missingProblems = localeFiles
            .filter { it.parentFile.name != "values" }
            .mapNotNull { file ->
                val missing = (base - namesIn(file)).sorted()
                if (missing.isEmpty()) null
                else "${file.parentFile.name} is missing: ${missing.joinToString(", ")}"
            }

        val entryRegex = Regex("<(string|item)\\b[^>]*>(.*?)</\\1>", RegexOption.DOT_MATCHES_ALL)
        val nonPositionalArgument = Regex("%[sd]")
        val escapedQuote = Regex("\\\\['\"]")
        val syntaxProblems = localeFiles.flatMap { file ->
            entryRegex.findAll(file.readText()).mapNotNull { match ->
                val text = match.groupValues[2].trim()
                when {
                    nonPositionalArgument.containsMatchIn(text) ->
                        "${file.parentFile.name}: non-positional argument in \"$text\" (use %1\$s / %1\$d)"
                    escapedQuote.containsMatchIn(text) ->
                        "${file.parentFile.name}: escaped quote in \"$text\" (write ' and \" unescaped)"
                    else -> null
                }
            }.toList()
        }

        val problems = missingProblems + syntaxProblems

        if (problems.isNotEmpty()) {
            error(
                buildString {
                    appendLine("Translation parity check failed.")
                    appendLine()
                    problems.forEach { appendLine("  • $it") }
                    appendLine()
                    appendLine("Add missing entries (or remove a locale that is no longer maintained), and keep")
                    appendLine("strings positional and unescaped — see the comment at the top of values/strings.xml.")
                }
            )
        }
        marker.get().asFile.apply {
            parentFile.mkdirs()
            writeText("ok: every values-* locale covers all ${base.size} entries in values/\n")
        }
    }
}

tasks.named("check") { dependsOn(verifyTranslationParity) }
